### ISSUE TITLE
Issue in auto-gen.py

### ISSUE THREAD

**Issue by 01shadowalker01** [BlackIQ/Hello-World#100]
Hey!
I think there is some problem with the `auto-gen.py`.
It didn't add Jython language correctly to the `README.md` file,
so I had to add it manually.
It removes my name from that line after you run the script!

**Comment by parsampsh** [comment]
This script does not re-write the exists file. If you add it and put the content, your file will not be over write.

**Comment by parsampsh** [comment]
You should create `Jython/info.json`. DO NOT change `README.md`

**Comment by amireshoon** [comment]
Read [contributing](https://github.com/BlackIQ/Hello-World/blob/main/CONTRIBUTING.md) guide for some more information.
