### ISSUE TITLE
Multiple contributors

### ISSUE THREAD

**Issue by amireshoon** [BlackIQ/Hello-World#122]
Due to PR #121 ,I realized that we should make info.json support multiple contributors for example one person adds Hello-World and someone adds data types in this case.

**Comment by parsampsh** [comment]
Yes this is perfect idea. I'll work on that.

**Comment by amireshoon** [comment]
@parsampsh let me know if you want any help.

**Comment by parsampsh** [comment]
Done. I'll create the pull request.

**Comment by amireshoon** [comment]
Fixed by @parsampsh  in PR #123
