### ISSUE TITLE
Cleanup languages adder lists

### ISSUE THREAD

**Issue by parsampsh** [BlackIQ/Hello-World#124]
Now we can add multiple creators to `info.json` of languages. We should make a cleanup on them and add list of other people contributed to that language.

**Comment by amireshoon** [comment]
What cleanup exactly do you mean?

**Comment by parsampsh** [comment]
> What cleanup exactly do you mean?

Adding list of new people to `info.json`s. (For example name of who added more example and who completed readme or added courses and books)
