### ISSUE TITLE
Haven't some languages 

### ISSUE THREAD

**Issue by Amirmohammadkazemi** [BlackIQ/Hello-World#132]
Lisp
Prolog
Java script

**Comment by amireshoon** [comment]
Hi, We already added those languages and you can find them in [Lisp](https://github.com/BlackIQ/Hello-World/tree/main/Lisp) [Prolog](https://github.com/BlackIQ/Hello-World/tree/main/Prolog) [JavaScript](https://github.com/BlackIQ/Hello-World/tree/main/JavaScript)
