### ISSUE TITLE
Kotlin has two directories

### ISSUE THREAD

**Issue by SM2A** [BlackIQ/Hello-World#197]
Kotlin language is having two directories, one with small and one with capital 'k'.
Cloning repository on Windows only make one in working tree.

**Comment by BlackIQ** [comment]
Hi,

We checked and there is only on Kotlin in [this link](https://github.com/BlackIQ/Hello-World/tree/main/Kotlin).

Link your second directory down below.

**Comment by SM2A** [comment]
https://github.com/BlackIQ/Hello-World/tree/main/kotlin

**Comment by BlackIQ** [comment]
Oh, tnx. We will fix this issue.
