### ISSUE TITLE
Contribution ways for this project

### ISSUE THREAD

**Issue by parsampsh** [BlackIQ/Hello-World#47]
I Think this repository is cool thing. we can provide a complete list from programming languages. Only a hello world example is low. we can add more examples from that programming languages and make this repo complete and complete.

**Comment by BlackIQ** [comment]
Exactly . we can put simple variable , conditions , loops and other important things in the language dir .

Like :
Python
|__main.py
|__Learn
    |__loop.py
    |__condition.py
    |__variables.py
    |__README.md

**Comment by parsampsh** [comment]
Also we can write something like a tutorial alongside them. also this makes this repo a tutorial source for lot of programming languages.

**Comment by BlackIQ** [comment]
Agreed . We can talk in Telegram too .
Sent you a message .

**Comment by BlackIQ** [comment]
We'll talk and decide what to do exactly .
I'll tell my friends to do this too .

**Comment by parsampsh** [comment]
Contribution ways:
- adding new languages
- adding new examples for current languages
- help to complete `README.md` file in language folder (`lang-name/README.md`)
- add link of useful books to books list for languages (`lang-name/books.md`)
- add link of useful courses to courses list for languages (`lang-name/courses.md`)

The above items are good ways to help us and contribute to this project. This make us happy :)

**Comment by parsampsh** [comment]
> Contribution ways:
> 
>     * adding new languages
> 
>     * adding new examples for current languages
> 
>     * help to complete `README.md` file in language folder (`lang-name/README.md`)
> 
>     * add link of useful books to books list for languages (`lang-name/books.md`)
> 
>     * add link of useful courses to courses list for languages (`lang-name/courses.md`)
> 
> 
> The above items are good ways to help us and contribute to this project. This make us happy :)

@BlackIQ is good to add above list to `CONTRIBUTING.md` file?

**Comment by BlackIQ** [comment]
Yes , awesome .
Anyway , I'm working on Courses and Books and language description .

**Comment by nantharupan** [comment]
Could you also a TODO list for each programming language for the examples you want to have. So we can contribute to the examples.

**Comment by BlackIQ** [comment]
That is a nice idea .
We'll talk and do it .

Thanks .
Amir .

**Comment by ali0gamer1** [comment]
Adding several examples and testing them for these languages is really time consuming.
But I think it's worth it.

**Comment by parsampsh** [comment]
> Adding several examples and testing them for these languages is really time consuming.
> But I think it's worth it.

slowly... :)

**Comment by ali0gamer1** [comment]
In some cases can we put links for more in-depth tutorials?

**Comment by parsampsh** [comment]
> In some cases can we put links for more in-depth tutorials?

Why not.

**Comment by parsampsh** [comment]
With #117 , i think we don't need this issue.
