### ISSUE TITLE
Put profile picture of the user who added lang before its name

### ISSUE THREAD

**Issue by BlackIQ** [BlackIQ/Hello-World#67]
Hello ,

We have a script that add creator and link after lang . But how about put the picture before !?

Example :

- Assembly - [Assembly](/Assembly) - Added By <img src="https://avatars.githubusercontent.com/u/42321156?s=460&u=7003d9df79e8b8b1bf0f277308ba03a173491f94&v=4" width="20" height="20">  [Taha Farahani](https://github.com/tahacodes)

Thanks .
May the force be with you .
Amir .

**Comment by parsampsh** [comment]
We only need to find user's profile image file link by the username. then script can add the image before the name

**Comment by BlackIQ** [comment]
It would take time to collect images from internet .
I think we can make a directory and put pictures there . Then , we use them .

**Comment by amireshoon** [comment]
I think it's better to use Github Discussions about this kind of stuff, And after the idea take a place we can create an issue for that.

**Comment by BlackIQ** [comment]
Agreed .

**Comment by amireshoon** [comment]
@BlackIQ I created the thread. https://github.com/BlackIQ/Hello-World/discussions/68

**Comment by parsampsh** [comment]
> It would take time to collect images from internet .
> I think we can make a directory and put pictures there . Then , we use them .

NO! we only need to put link of the image from github. we don't need to keep images in the repository!

**Comment by parsampsh** [comment]
It's done.
