### ISSUE TITLE
tree.txt conflicts in github workflow

### ISSUE THREAD

**Issue by parsampsh** [BlackIQ/Hello-World#98]
I added a part to `auto-gen.py` to automatically generate `tree.txt` file. Also this will be generated in github workflow. But the matter is that, `tree` command generates different output in different platforms. Only sort of files is different. Is any idea? is any option for `tree` command to sync sort of files with one algo?

**Comment by parsampsh** [comment]
I Also tried `tree --dirsfirst -r` But not solved. `tree` output sort is different in github actions with my computer.

**Comment by parsampsh** [comment]
I disabled `tree.txt` auto generation in `auto-gen.py` temporarily. If there is any idea, please tell me to fix it. Thanks.

**Comment by parsampsh** [comment]
Is useful `--sort=name` option?

**Comment by BlackIQ** [comment]
> Is useful `--sort=name` option?

Weird . Thought `tree` is same in all distro . But now , should think and find a way to solve it .
It isn't important . We'll work on that .

**Comment by parsampsh** [comment]
> > Is useful `--sort=name` option?
> 
> Weird . Thought `tree` is same in all distro . But now , should think and find a way to solve it .
> It isn't important . We'll work on that .

Ok. i'll test `--sort=name`

**Comment by parsampsh** [comment]
> > > Is useful `--sort=name` option?
> > 
> > 
> > Weird . Thought `tree` is same in all distro . But now , should think and find a way to solve it .
> > It isn't important . We'll work on that .
> 
> Ok. i'll test `--sort=name`

Didn't worked.

**Comment by parsampsh** [comment]
Fixed by @amireshoon at #101.
